// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJZjQ4Sjj4rOinY8IIEds_13mBMgxEp5U',
    appId: '1:1012066477806:web:9993a7ae2a38356c9cf5ff',
    messagingSenderId: '1012066477806',
    projectId: 'event-app-c8926',
    authDomain: 'event-app-c8926.firebaseapp.com',
    storageBucket: 'event-app-c8926.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO-XUS90vymrDnVil1Hxbo7EOhIH4lOHI',
    appId: '1:1012066477806:android:a12da4878e6cf3e59cf5ff',
    messagingSenderId: '1012066477806',
    projectId: 'event-app-c8926',
    storageBucket: 'event-app-c8926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgkToCcMOLATRGDyRQCdiUQKIKJtAX5_w',
    appId: '1:1012066477806:ios:6d73b063b23960b39cf5ff',
    messagingSenderId: '1012066477806',
    projectId: 'event-app-c8926',
    storageBucket: 'event-app-c8926.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgkToCcMOLATRGDyRQCdiUQKIKJtAX5_w',
    appId: '1:1012066477806:ios:6d73b063b23960b39cf5ff',
    messagingSenderId: '1012066477806',
    projectId: 'event-app-c8926',
    storageBucket: 'event-app-c8926.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJZjQ4Sjj4rOinY8IIEds_13mBMgxEp5U',
    appId: '1:1012066477806:web:be6ff884dbac10829cf5ff',
    messagingSenderId: '1012066477806',
    projectId: 'event-app-c8926',
    authDomain: 'event-app-c8926.firebaseapp.com',
    storageBucket: 'event-app-c8926.firebasestorage.app',
  );
}
